TravelTripCoreProject/Models/Classes/About.cs
using System;
using System.Collections.Generic;

namespace TravelTripCoreProject.Models.Classes;

public partial class About
{
    public int Id { get; set; }

    public string? PhotoUrl { get; set; }

    public string? Description { get; set; }
}

TravelTripCoreProject/Models/Classes/Contact.cs
using System;
using System.Collections.Generic;

namespace TravelTripCoreProject.Models.Classes;

public partial class Contact
{
    public int Id { get; set; }

    public string? NameSurname { get; set; }

    public string? Email { get; set; }

    public string? Subject { get; set; }

    public string? Message { get; set; }
}

TravelTripCoreProject/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using TravelTripCoreProject.Business.Services;
using TravelTripCoreProject.DataAccessLayer.Contexts;
using TravelTripCoreProject.Models.Classes;

namespace TravelTripCoreProject.Controllers
{
    public class MainController(IBlogService blogService, IContactService contactService, IAboutService aboutService) : Controller
    {
        private readonly IBlogService _blogService = blogService;
        private readonly IContactService _contactService = contactService;
        private readonly IAboutService _aboutService = aboutService;

        public IActionResult Index()
        {
            var values = _blogService.GetAllBlogs().Take(6).ToList();

            return View(values);
        }
        public IActionResult About()
        {
            var values = _aboutService.GetAll();
            return View(values);
        }
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Contact(string name, string email, string message, string subject)
        {
            var result = _contactService.AddContact(new Contact
            {
                NameSurname = name,
                Email = email,
                Message = message,
                Subject = subject
            });
            ViewBag.Message = result ? "Mesajınız alındı!" : "Bir hata oluştu.";
            return View();
        }
    }
}

TravelTripCoreProject/ViewsComponents/Partial1ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TravelTripCoreProject.DataAccessLayer.Contexts;

namespace TravelTripCoreProject.ViewsComponents
{
    public class Partial1ViewComponent : ViewComponent
    {
        private readonly Context _context;
        public Partial1ViewComponent(Context context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            var values = _context.Blogs.Take(2).ToList();
            return View(values); // View yolu: Views/Shared/Components/Partial1/Default.cshtml
        }
    }
}

TravelTripCoreProject/ViewsComponents/Partial3ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TravelTripCoreProject.DataAccessLayer.Contexts;

namespace TravelTripCoreProject.ViewsComponents
{
    public class Partial3ViewComponent : ViewComponent
    {
        private readonly Context _context;
        public Partial3ViewComponent(Context context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            var values = _context.Blogs.Take(10).ToList();
            return View(values);
        }
    }
}

TravelTripCoreProject/ViewsComponents/Partial4ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TravelTripCoreProject.DataAccessLayer.Contexts;

namespace TravelTripCoreProject.ViewsComponents
{
    public class Partial4ViewComponent : ViewComponent
    {
        private readonly Context _context;
        public Partial4ViewComponent(Context context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {
            var value = _context.Blogs.Take(3).ToList();
            return View(value);
        }
    }
}

TravelTripCoreProject/Views/Main/About.cshtml
@using TravelTripCoreProject.Models.Classes
@model List<About>
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="content">
    <div class="wrap">
        <div class="about">
            <h3>Hakkımızda</h3>
            @foreach (var item in Model)
            {
                <img src="@item.PhotoUrl" alt="" />
                <p>@item.Description</p>

            }

        </div>
    </div>
</div>

TravelTripCoreProject/Views/Main/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
<link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
<div class="single">
    <div class="container">
        <div class="col-md-8 single-main">
            <div class="content-form">
                @if (ViewBag.Message != null)
                {
                    <div>@ViewBag.Message</div>
                }
                <h3>İletişim</h3>
                <form method="post">
                    <input type="text" name="name" placeholder="Adınız" required />
                    <input type="text" name="email" placeholder="Email" required />
                    <input type="text" name="subject" placeholder="Konu" required />
                    <textarea name="message" placeholder="Mesajınız" required></textarea>
                    <input type="submit" value="Gönder" />
                </form>
            </div>
        </div>
    </div>
</div>

TravelTripCoreProject/Views/Main/Index.cshtml
@using TravelTripCoreProject.Models.Classes
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>
    
    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot">Gezinizi Kolayca Planlayın</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restoranlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Uçuşlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Yapılacak Aktiviteler</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Araç Kiralama</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider">
                            <ul class="rslides" id="slider1">
                                @foreach (var item in Model)
                                {
                                    <li><img src="@item.BlogImage" alt="" style="width: 650px; height:400px"></li>

                                }
                                
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>Tatil Seyahat Bloguna Hoşgeldiniz!</h3>
                    <p>Bu projeyi Şubat 2025 tarihinde başlatıp yine Şubat 2025 tarihinde
                    ana sayfa düzenlemelerine getirdik. Gezip gördüğüm yerleri sizlerle
                    paylaşmak için kodlamasını tamamen kendim yaptığım mvc5 üzerine kurulu
                    dinamik bir web projesi geliştirdik. Hem Türkiye'den hem de yurtdışından
                    gezip gördüğüm yerleri blog yazıları olarak sizlerle paylaşma niyetindeyim.
                     Umuyorum ki yazdıklarımı beğenirsiniz, keyifli okumalar, sağlıklı günler.</p>
                </div>

                @await Component.InvokeAsync("Partial1")
                
                <div class="grids">
                    <div class="box1">
                        @await Component.InvokeAsync("Partial3")
                        @await Component.InvokeAsync("Partial4")
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>