TravelTripCoreProject/Models/Classes/Blog.cs
using System;
using System.Collections.Generic;

namespace TravelTripCoreProject.Models.Classes;

public partial class Blog
{
    public int Id { get; set; }

    public string? Title { get; set; }

    public DateTime DateTime { get; set; }

    public string? Description { get; set; }

    public string? BlogImage { get; set; }
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();
}

TravelTripCoreProject/Models/Classes/BlogDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace TravelTripCoreProject.Models.Classes
{
    public class BlogDetailViewModel
    {
        public Blog Blog { get; set; }
        public List<Comment> Comments { get; set; }
        public List<Blog> LastBlogs { get; set; }
    }
}

TravelTripCoreProject/Models/ViewModels/BlogDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using TravelTripCoreProject.Models.Classes;

namespace TravelTripCoreProject.Models.ViewModels
{
    public class BlogDetailViewModel
    {
        public Blog Blog { get; set; }
        public List<Comment> Comments { get; set; }
        public List<Blog> LastBlogs { get; set; }
    }
}

TravelTripCoreProject/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelTripCoreProject.Models.Classes;
using Newtonsoft.Json;
using TravelTripCoreProject.Models;
using TravelTripCoreProject.DataAccessLayer.Contexts;
using TravelTripCoreProject.Business.Services;
using TravelTripCoreProject.Models.ViewModels;

namespace TravelTripCoreProject.Controllers
{
    public class BlogController(IBlogService blogService, ICommentService commentService) : Controller
    {
        private readonly IBlogService _blogService = blogService;
        private readonly ICommentService _commentService = commentService;

        public IActionResult Index(int? i)
        {
            int pageSize = 5;
            int pageNumber = i ?? 1;
            int skip = (pageNumber - 1) * pageSize;

            var blogs = _blogService.GetPagedBlogs(skip, pageSize).ToList();
            int totalItems = _blogService.GetAllBlogs().Count;

            var viewModel = new BlogListViewModel
            {
                Blogs = blogs,
                TotalItems = totalItems,
                HasNextPage = (skip + pageSize) < totalItems,
                HasPreviousPage = pageNumber > 1,
                CurrentPage = pageNumber,
                PageSize = pageSize
            };

            return View(viewModel);
        }
        public IActionResult BlogDetail(int id)
        {
            var blog = _blogService.GetById(id);
            if (blog == null)
                return NotFound();
            BlogDetailViewModel viewModel = new BlogDetailViewModel
            {
                Blog = blog,
                Comments = _commentService.GetCommentsByBlogId(id),
                LastBlogs = _blogService.GetAllBlogs()
                    .OrderByDescending(b => b.DateTime)
                    .Take(3)
                    .ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult LeaveComment(int blogId, string username, string email, string userComment)
        {
            var comment = _commentService.AddComment(blogId, username, email, userComment);
            if (comment != null)
            {
                // Yorum başarıyla eklendi.
                return RedirectToAction("BlogDetail", new { id = blogId });
            }
            else
            {
                // Hata durumu
                ModelState.AddModelError("", "Yorum eklenemedi.");
                return View();
            }
        }

    }
}

TravelTripCoreProject/ViewsComponents/LeaveCommentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TravelTripCoreProject.Models.Classes;

namespace TravelTripCoreProject.ViewsComponents
{
    public class LeaveCommentViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int id)
        {
            var model = new Comment { BlogId = id };
            return View(model);
        }
    }
}

TravelTripCoreProject/Views/Blog/BlogDetail.cshtml
@using TravelTripCoreProject.Models.Classes

@model TravelTripCoreProject.Models.ViewModels.BlogDetailViewModel
@{
    ViewBag.Title = "BlogDetail";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->

</head>
<body>

    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                <div class="single-grid">
                    <img src="@Model.Blog.BlogImage" alt="" />
                    <h2>@Model.Blog.Title</h2>
                    <p>
                        @Model.Blog.Description
                    </p>
                </div>
                @if(Model.Comments != null && Model.Comments.Any()) 
                {
                    @foreach (var comment in Model.Comments)
                    {
                        <ul class="comment-list">
                            <li>
                                <img src="~/web2/images/avatar.png" class="img-responsive" alt="">
                                <div class="desc">
                                    <p>@comment.Username: @comment.UserComment </p>
                                </div>
                                <div class="clearfix"></div>
                            </li>
                        </ul>

                    }
                }
                
                @await Component.InvokeAsync("LeaveComment", new { id = Model.Blog.Id })


            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>Son Bloglar</h3>
                    <ul>
                        @foreach (var lastBlog in Model.LastBlogs)
                        {
                            <li><a href="@Url.Action("BlogDetail","Blog", new {id = lastBlog.Id})">@lastBlog.Title</a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

TravelTripCoreProject/Views/Blog/Index.cshtml
@using TravelTripCoreProject.Models.ViewModels
@using X.PagedList
@using X.PagedList.Mvc.Core

@model BlogListViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var blog in Model.Blogs)
                {
                    <div class="single-grid">
                        <img src="@blog.BlogImage" alt="" style="margin-bottom: 20px" />
                        <br />
                        <h4><a href="@Url.Action("BlogDetail","Blog",new {id = blog.Id})">@blog.Title</a></h4>
                        @{
                            string desc = blog.Description ?? "";
                            string shortDesc = desc.Length > 200 ? desc.Substring(0, 200) + "..." : desc;
                        }
                        <p>@shortDesc</p>
                    </div>
                    <br />
                    <br />
                }

                <!-- Klasik Pagination HTML'i -->
                <div class="pagination">
                    @if (Model.HasPreviousPage)
                    {
                        <a href="@Url.Action("Index", "Blog", new { i = Model.CurrentPage - 1 })">Önceki</a>
                    }
                    @for (int pageNum = 1; pageNum <= (int)Math.Ceiling((double)Model.TotalItems / Model.PageSize); pageNum++)
                    {
                        if (pageNum == Model.CurrentPage)
                        {
                            <span style="font-weight: bold">@pageNum</span>
                        }
                        else
                        {
                            <a href="@Url.Action("Index", "Blog", new { i = pageNum })">@pageNum</a>
                        }
                    }
                    @if (Model.HasNextPage)
                    {
                        <a href="@Url.Action("Index", "Blog", new { i = Model.CurrentPage + 1 })">Sonraki</a>
                    }
                </div>
            </div>

            @* <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>Son Bloglar</h3>
                    <ul>
                        @foreach (var lastBlog in Model.LastBlogs)
                        {
                            <li><a href="@Url.Action("BlogDetail","Blog", new {id = lastBlog.Id})">@lastBlog.Title</a></li>
                        }
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div> *@
        </div>
    </div>
</body>
</html>

TravelTripCoreProject/Views/Blog/LeaveComment.cshtml
@model TravelTripCoreProject.Models.Classes.Comment

<div class="content-form">
    <h3>Bir Yorum Yapın</h3>
    <form method="post">
        <input type="hidden" name="blogId" value="@ViewBag.value" required/>
        <input type="text" placeholder="Kullanıcı Adı" name="username" required />
        <input type="text" placeholder="Email" name="email" required />
        <textarea placeholder="Yorum" name="userComment" required></textarea>
        <input type="submit" value="Gönder" />
    </form>
</div>